# This project uses the GitFlow Workflow as defined here:
#   https://www.atlassian.com/git/tutorials/comparing-workflows#GitFlow-workflow
image: node:alpine

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            # install ASW CLI, jq library, node
            - npm install
            - apk --no-cache update && apk --no-cache add python py-pip py-setuptools ca-certificates curl groff less && pip --no-cache-dir install awscli && rm -rf /var/cache/apk/*
            - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
            # build docker image and push to nexus.interopion.com:18083 (docker-interopion)
            - export IMAGE_NAME=$(cat container-definitions_test.json | jq --raw-output '.[0].image')
            - docker login -u $NEXUS_USR -p $NEXUS_PWD nexus.hspconsortium.org:18083
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
            # register the ECS task definition and capture the version
            - export TASK_VERSION=$(aws ecs register-task-definition --family hspc-sandbox-manager --container-definitions $(cat container-definitions_test.json | jq -c '.')  | jq --raw-output '.taskDefinition.revision')
            - echo "Registered ECS Task Definition - " $TASK_VERSION
            # update the service to use the latest task definition
            - aws ecs update-service --cluster $TARGET_AWS_CLUSTER --service $TARGET_AWS_SERVICE --task-definition hspc-sandbox-manager:$TASK_VERSION
    feature/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    release/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    hotfix/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    master:
      - step:
          script:
            # Deploy to maven central
            - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --import private-key.gpg
            - mvn -V -B -s settings.xml deploy -P DEPLOY,ossrh
            # Deploy to hspc-nexus
            - mvn -V -B -s settings.xml deploy -P DEPLOY-HSPC,hspc-nexus
            # install ASW CLI and jq library
            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            - unzip awscli-bundle.zip
            - ./awscli-bundle/install -b ~/bin/aws
            - export PATH=~/bin:$PATH
            - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
            # build docker image and push to nexus.interopion.com:18083 (docker-interopion)
            - export IMAGE_NAME=$(cat container-definitions_test.json | jq --raw-output '.[0].image')
            - docker login -u $NEXUS_USR -p $NEXUS_PWD nexus.hspconsortium.org:18083
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
options:
  docker: true