# This project uses the GitFlow Workflow as defined here:
#   https://www.atlassian.com/git/tutorials/comparing-workflows#GitFlow-workflow
image: hspconsortium/hspc-ubuntu-base
clone:           # the 'clone' section
  depth: 1       # the depth, in this case the clone will contain last one commits

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            # set active_env with current environment
            - sed -i -e 's/replacethiswithcurrentenvironment/test/g' ./src/static/js/services.js
            - . ci-all.sh
    feature/*:
      - step:
          caches:
            - node
          script:
            - npm install
    release/*:
      - step:
          caches:
            - node
          script:
            - npm install
    hotfix/*:
      - step:
          caches:
            - node
          script:
            - npm install
    master:
      - step:
          caches:
            - node
          script:
            # install ASW CLI, jq library, node
            - sed -i -e 's/replacethiswithcurrentenvironment/prod/g' ./src/static/js/services.js
            - . ci-all.sh
options:
  docker: true