version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: sandman
       MYSQL_USER: sandmanapi
       MYSQL_PASSWORD: password

   sandman_api:
     depends_on:
       - db
     image: nexus.hspconsortium.org:18082/hspc/hspc-sandbox-manager-api:0.6.0-SNAPSHOT
     ports:
       - "12000:12000"
     restart: always
     environment:
       DB_HOST: db:3306
       DB_USER: sandmanapi
       DB_PASSWORD: password

   sandman:
     image: nexus.hspconsortium.org:18082/hspc/hspc-sandbox-manager:2.6.8
     ports:
       - "8080:8080"
     restart: always

volumes:
    db_data: